language: node_js
node_js:
  - 16.13.1
dist: xenial
sudo: required
branches :
    only: 
       - master
before_script:
 - npm install -g firebase-tools
 - npm install -g @angular/cli
script:
 - npm install
 - ng test --watch=false --browsers=Chromeheadless
 - npm run build
deploy:
 skip_cleanup: True 
 provider: firebase 
 project: toronto-weather-e4751 
after_sucess:
 firebase deploy --token $FIREBASE_TOKEN
